name: My first workflow

on: [push]

jobs:
  First_job:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome message
        run: echo "Hello All in today's class"

      - name: checkout
        run: actions/checkout@v6

      - name: List all the file
        run: ls

      - name: Read the file
        run: cat README.md